### ISSUE TITLE
Problem when deparsing a query with multiple columns in parentheses in "GroupBy Clause"

### ISSUE THREAD

**Issue by primeapple** [pganalyze/pg_query#127]
Hi, back here with another issue:

When we have a query like 
```sql
SELECT id, name, count(grade) FROM student GROUP BY (id, name)
```
It is the same as
```sql
SELECT id, name, count(grade) FROM student GROUP BY id, name
```
However it is not the same as:
```sql
SELECT id, name, count(grade) FROM student GROUP BY ROW (id, name)
```
as the last one is not executable anymore (error: `column "student.id" must appear in the GROUP BY clause or be used in an aggregate function `

I am not so sure how GROUP BY ROW works, so please have a look over it :)

**Comment by lfittl** [comment]
Fixed in 2.0!

```
irb(main):017:0> PgQuery.parse('SELECT id, name, count(grade) FROM student GROUP BY (id, name)').deparse
=> "SELECT id, name, count(grade) FROM student GROUP BY (id, name)"
```
