### ISSUE TITLE
Deparse changes type "float" to non-existing type "double"

### ISSUE THREAD

**Issue by primeapple** [pganalyze/pg_query#130]
Filling your issuelist up!

We have a query where we do casting
```sql
SELECT CAST(id AS float) FROM student
```
First of all, I'm very amazed, that this can be deparsed at all. It really shows how deep you dived into this and I very much appreciate it!
However we have a little problem, the query is deparsed to:
```sql
SELECT "actor_id"::double FROM "actor"
```
which can't be executed (at least in my postgres version) because:
`ERROR: type \"double\" does not exist`

**Comment by lfittl** [comment]
This is has been fixed via https://github.com/pganalyze/pg_query/pull/139 (and is also fixed in the 2.0 release)
