### ISSUE TITLE
Deparse drops parentheses in Expressions

### ISSUE THREAD

**Issue by primeapple** [pganalyze/pg_query#131]
This one is quite important, it gave me troubles a lot of times:
Consider the query, to show all students with an ID between 5 and 8 (6,7):
```sql
SELECT * FROM student WHERE NOT (id > 5 AND id < 8)
```
When we parse and deparse it we get:
```sql
SELECT * FROM "student" WHERE NOT "id" > 5 AND "id" < 8
```
Which is all the students with and ID below 8 and not over 5, so 0,1,2,3,4,5.

This one happens a lot of times in expressions!

Bonus:
Parenthesis are also dropped in JOINs:
`FROM (student JOIN class using(id)) sc` gets `FROM student JOIN class using(id)`

**Comment by lfittl** [comment]
Fixed in pg_query 2.0!

```
irb(main):007:0> PgQuery.parse('SELECT * FROM student WHERE NOT (id > 5 AND id < 8)').deparse
=> "SELECT * FROM student WHERE NOT (id > 5 AND id < 8)"
irb(main):008:0> PgQuery.parse('SELECT * FROM "student" WHERE NOT "id" > 5 AND "id" < 8').deparse
=> "SELECT * FROM student WHERE NOT id > 5 AND id < 8"
```
