### ISSUE TITLE
Improve Parser and Deparser

### ISSUE THREAD

**Issue by emin100** [pganalyze/pg_query#144]
Hi,

I extract sql examples in PostgreSQL documentation and test with pg_query. I'm thinking of fixing it all. How should we proceed? Results and errors:
[Test Results](https://github.com/emin100/extract_postgresql_documentation_sql_examples/blob/master/results/deparse_.result)
[Parser Errors](https://github.com/emin100/extract_postgresql_documentation_sql_examples/blob/master/results/deparse_parser_error.result)
[Deparser Errors](https://github.com/emin100/extract_postgresql_documentation_sql_examples/blob/master/results/deparse_deparser_error.result)
[Have Diffrent Fingerprint](https://github.com/emin100/extract_postgresql_documentation_sql_examples/blob/master/results/deparse_diff_fingerprint.result)
[Pass The Test](https://github.com/emin100/extract_postgresql_documentation_sql_examples/blob/master/results/deparse_ok.result)

Extract and Test codes in https://github.com/emin100/extract_postgresql_documentation_sql_examples.git

**Comment by lfittl** [comment]
Nice, thats a great effort!

We could consider using your logic in `extract.rb` to automatically generate the deparse tests - i.e. have a Ruby spec read a JSON file or similar, that has the SQL statements to be tested.

To start with, maybe we can pick one subsection of the documentation, agree on the extract/test approach (and how it can be integrated here), and then we proceed with the other sections?

I'll let you pick which one makes most sense to tackle first :)

**Comment by lfittl** [comment]
Oh, and also a minor note: I realize your repository is licensed under GPL. Please note that this repository is licensed under MIT license, so any contribution is considered to be made under the MIT license as well.

Its your choice if you'd like to contribute of course (and thus relicense your code), but wanted to point this out to be clear.

**Comment by emin100** [comment]
I change the license BSD-3-Clause. Is this okay for you?

**Comment by emin100** [comment]
Make sense, automatically generate the deparse tests. Then, In order of importance, we can choose which ones to fix first.

**Comment by lfittl** [comment]
@emin100 I think with the new deparser in the 2.0 release, this should address all known limitations with the deparser.

I'll close this issue for now, and wanted to thank you again for your many contributions over the years. It has helped a lot to write the new C-based deparser, to have all the examples you have provided :)
