### ISSUE TITLE
Is there a complete list of nodes and a node's information?

### ISSUE THREAD

**Issue by ZhirongYuan0628** [pganalyze/pg_query#160]
Hi, your work is impressive :) I have some doubts, what is the complete format of parsetree's json? I will need it because I need to traverse the parsetree to extract specific information.
For example, the parse tree of PgQuery.parse ("select count (*) from page") has node FunCall, while PgQuery.parse ("select * from page") does not. If I don't know the existence of FunCall node, it will make my traversal difficult.
Also, I cannot know the meaning of the "CommonTableExpr" node in "WithClause"? What information does this node contain? I am also confused about some other nodes
Is there a complete list of nodes and what does each node mean?

**Comment by lfittl** [comment]
@ZhirongYuan0628 The new 2.0 release now has full class types for each node, making it much easier to to what you're describing.

You can see this in the example in the README here: https://github.com/pganalyze/pg_query#parsing-a-query

They are based on the Protobuf format of the parse tree, you can see it for reference here: https://github.com/pganalyze/libpg_query/blob/13-latest/protobuf/pg_query.proto
