### ISSUE TITLE
Fails to build version 2.0.3 - "unknown type name 'PgQueryProtobuf'"

### ISSUE THREAD

**Issue by VVD** [pganalyze/pg_query#215]
FreeBSD 12.2 amd64, ruby 2.7.3.
1st error during build is:
```
In file included from /usr/ports/databases/rubygem-pg_query/work/stage/usr/local/lib/ruby/gems/2.7/gems/pg_query-2.0.3/ext/pg_query/pg_query_deparse.c:3:
./pg_query_readfuncs.h:9:35: error: unknown type name 'PgQueryProtobuf'
List * pg_query_protobuf_to_nodes(PgQueryProtobuf protobuf);
```
Bug report for FreeBSD port databases/rubygem-pg_query: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=256741

What other info do you need?

**Comment by lfittl** [comment]
@VVD Per the discussion on the FreeBSD bug report, this looks like a problem if `libpg_query` is also installed on the system and in the include path.

I think the problem might be that the system include paths get listed first in the generated Makefile, and therefore the installed `libpg_query` library takes precedence, which in this case is an older version of `libpg_query` (before the 2.0 release, thus missing the `PgQueryProtobuf` struct).

Here is an attempt at fixing this: https://github.com/pganalyze/pg_query/pull/216

Could you see whether this resolves the issue? (you'd have to do a manual build from the source branch on a machine that has the FreeBSD port installed for libpg_query)

**Comment by lfittl** [comment]
@VVD I ended up releasing this with the 2.1.0 release - I'm fairly certain this resolves the problem, so I'll close this issue for now.

If you could confirm, and report back that would be great. We can reopen the issue in case this is still causing problems.

**Comment by VVD** [comment]
It build fine with this patch!
Thanks!
