### ISSUE TITLE
Can't install with Ruby 3.1.1

### ISSUE THREAD

**Issue by feliperaul** [pganalyze/pg_query#247]
I'm getting this message when trying to install with latest ruby 3.1.1 on a Mac:

`google-protobuf-3.19.4-x86_64-darwin requires ruby version < 3.1.dev, >= 2.5, which is incompatible with the current version, ruby 3.1.1p18`

**Comment by olleolleolle** [comment]
I guess that gem install google-protobuf also fails on Ruby 3.1.1 - if yes, then we are waiting for google-protobuf to support 3.1.1.

**Comment by johnnyshields** [comment]
Ruby 3.1 is still not working on Windows. This PR should fix it: https://github.com/protocolbuffers/protobuf/pull/9963

**Comment by lfittl** [comment]
Closing this, since 3.1 has been supported for a while now.
