### ISSUE TITLE
Seg Fault due to new protobuf release

### ISSUE THREAD

**Issue by jonyscathe** [pganalyze/pg_query#261]
See: https://github.com/protocolbuffers/protobuf/issues/10792

Until this issue is resolved (though 🤞 it will be fixed quickly), would it be possible to get a quick release with the protobuf dep set to >=3.19.2,  < 3.21.8 ?

**Comment by lfittl** [comment]
@jonyscathe Thanks for the report - this seems to be an Alpine related issue that they'll hopefully fix quickly.

Since this is hopefully a matter of a few days only, is there a reason you couldn't pin the protobuf version explicitly in your Gemfile?

**Comment by jonyscathe** [comment]
Hi, 
Yes that was what I ended up doing.
A bit of a pain as I didn't have a Gemfile (was just using sqlint to lint some SQL, which then used pg_query, which then used protobuf).
But at least now I've learnt about gemfiles.
And it looks like a new version of protobuf will be out shortly with a fix.
