### ISSUE TITLE
What's the correct way to recurse the tree?

### ISSUE THREAD

**Issue by directionless** [pganalyze/pg_query#267]
Hi! Forgive the question in issues. I'm porting some code from using v1 of this gem to v2, and I'm not really sure what the idiomatic way to recurse the tree is. 

For example, I want to change the table names. There's a very simple [example](https://github.com/pganalyze/pg_query#modifying-a-parsed-query-and-turning-it-into-sql-again) in the readme, but that doesn't seem to handle the complexity of the real world.

Poking around, I see the `treewalk!` function, which seems ideal. But, because it's private using it means extending or monkey patching. So I'm wondering if I'm missing an idiom.

For what it's worth, my table name change function feels pretty clean using treewalk:
```ruby
        # table_rewrite finds the table names, and re-writes them with a yield
        def table_rewriter
          treewalker! @tree do |node, k, v, location|
            # :range_var is used for select, and :relation is used for update.
            # Both have the same node structure
            next unless %i[range_var relation].include?(k)

            relname = v.relname
            next if relname.nil?

            # Skip over things that are not tables (CTEs for example)
            next unless tables.include?(relname)

            v.relname = yield relname
          end
        end
```

**Comment by directionless** [comment]
As I find edge cases, my code has gotten more complex, but I don't think it changes the overall question

**Comment by lfittl** [comment]
@directionless Good question!

I would actually support making `treewalker!` a public function, its private mostly for historic reasons.

As a workaround, you could always use `send(..)` but that's kind of a hack. Do you want to open a PR that makes that API change to make it public?
