### ISSUE TITLE
unable to build 0.5.0 version due to missing .tar.gz

### ISSUE THREAD

**Issue by pokefloats** [pganalyze/pg_query#271]
I completely understand that 0.5.0 was released 7 years ago, but I'm working on this project that utilizes code from 7 years which also includes the pg_query gem. Currently running Ruby 2.3.0.

I have to install pg_query 0.5.0, but it spits out this message.
```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

/home/3str/.rbenv/versions/2.3.0/lib/ruby/2.3.0/open-uri.rb:359:in `open_http': 404 Not Found (OpenURI::HTTPError)
        from /home/3str/.rbenv/versions/2.3.0/lib/ruby/2.3.0/open-uri.rb:737:in `buffer_open'
        from /home/3str/.rbenv/versions/2.3.0/lib/ruby/2.3.0/open-uri.rb:212:in `block in open_loop'
        from /home/3str/.rbenv/versions/2.3.0/lib/ruby/2.3.0/open-uri.rb:210:in `catch'
        from /home/3str/.rbenv/versions/2.3.0/lib/ruby/2.3.0/open-uri.rb:210:in `open_loop'
        from /home/3str/.rbenv/versions/2.3.0/lib/ruby/2.3.0/open-uri.rb:151:in `open_uri'
        from /home/3str/.rbenv/versions/2.3.0/lib/ruby/2.3.0/open-uri.rb:717:in `open'
        from /home/3str/.rbenv/versions/2.3.0/lib/ruby/2.3.0/open-uri.rb:35:in `open'
        from extconf.rb:33:in `block in <main>'
        from extconf.rb:32:in `open'
        from extconf.rb:32:in `<main>'
```

The line that causes this 404 not found is in commit d4a849edd8051cf2792bd5f2da03aea6203687dd:
```ruby
open("https://codeload.github.com/pganalyze/postgres/tar.gz/pg_query", "rb") do |read_file|
```

The repo this refers to, pganalyze/postgres, has been seemingly deleted(?)

Was wondering if the .tar.gz from postgres 9.3 from the pganalyze/postgres is still available to be downloaded

**Comment by lfittl** [comment]
@chadwardenlol Unfortunately that's no longer available (I just checked and there is no quick backup I could find either) - we changed the approach here to not rely on code being downloaded during installation, since that was error prone, exactly because of problems like this one here.

Therefore unfortunately this is not supported and we can't do anything to help here.
