### ISSUE TITLE
(Select Into) doesn't return DDL tables

### ISSUE THREAD

**Issue by OmarQunsul** [pganalyze/pg_query#280]
`select info` creates a new table, but the parsed query doesn't return any tables for `ddl_tables`

```
parsed = PgQuery.parse "select * into new_users from users"
parsed.ddl_tables # [] which is wrong, it should contain ["new_users"]
parsed.dml_tables # [] correct
```

Reference: https://www.postgresql.org/docs/current/sql-selectinto.html

**Comment by lfittl** [comment]
Thanks for the report!

Could you review whether https://github.com/pganalyze/pg_query/pull/281 fixes this as you'd expect it to work?

**Comment by OmarQunsul** [comment]
@lfittl yes, it works :100: thank you
