### ISSUE TITLE
4.2.1 On FreeBSD: pg_query_ruby_freebsd.sym: No such file or directory

### ISSUE THREAD

**Issue by mfechner** [pganalyze/pg_query#291]
Error:
```
63 warnings generated.
compiling /wrkdirs/usr/ports/databases/rubygem-pg_query/work/stage/usr/local/lib/ruby/gems/3.1/gems/pg_query-4.2.1/ext/pg_query/src_port_strnlen.c
warning: unknown warning option '-Wno-clobbered' [-Wunknown-warning-option]
warning: unknown warning option '-Wno-discarded-qualifiers'; did you mean '-Wno-ignored-qualifiers'? [-Wunknown-warning-option]
2 warnings generated.
compiling /wrkdirs/usr/ports/databases/rubygem-pg_query/work/stage/usr/local/lib/ruby/gems/3.1/gems/pg_query-4.2.1/ext/pg_query/xxhash.c
warning: unknown warning option '-Wno-clobbered' [-Wunknown-warning-option]
warning: unknown warning option '-Wno-discarded-qualifiers'; did you mean '-Wno-ignored-qualifiers'? [-Wunknown-warning-option]
2 warnings generated.
linking shared-object pg_query/pg_query.so
ld: error: cannot open /wrkdirs/usr/ports/databases/rubygem-pg_query/work/stage/usr/local/lib/ruby/gems/3.1/gems/pg_query-4.2.1/ext/pg_query/pg_query_ruby_freebsd.sym: No such file or directory
cc: error: linker command failed with exit code 1 (use -v to see invocation)
*** Error code 1
```

The full build log can be found here:
https://pkg.fechner.net/data/132amd64-gitlab/2023-06-23_10h06m34s/logs/errors/rubygem-pg_query-4.2.1.log

I checked the commit history and found the following commit that introduced a change I think is related to the problem:
https://github.com/pganalyze/pg_query/commit/684aa77a21eb46188de0ab9bfdabcef71f591614

But the file seems that the file does not exist or something is removing it.

If I testbuild the package:
```
poudriere testport -p gitlab -j 132amd64 -i databases/rubygem-pg_query
```
and I check in the sources after the build failed:
```
ls -las /wrkdirs/usr/ports/databases/rubygem-pg_query/work/stage/usr/local/lib/ruby/gems/3.1/gems/pg_query-4.2.1/ext/pg_query/pg_query_ruby_freebsd.sym
ls: /wrkdirs/usr/ports/databases/rubygem-pg_query/work/stage/usr/local/lib/ruby/gems/3.1/gems/pg_query-4.2.1/ext/pg_query/pg_query_ruby_freebsd.sym: No such file or directory
```

The problem is that the file `ext/pg_query/pg_query_ruby_freebsd.sym` is missing.
I tried next to manually add the file with a patch steps, but it looks that something in the build process removes the file.

I'm not sure if this is related to a behaviour in FreeBSD ports or if ruby while building is removing the file.

Maybe someone has an idea?

**Comment by lfittl** [comment]
Thanks for the report @mfechner!

Looks like we dropped the `ext/pg_query/pg_query_ruby_freebsd.sym` file in the 15 rebase: https://github.com/pganalyze/pg_query/pull/270/files#diff-70e83c8dad161358fdefbb4e3ade15b1ec39947e27ffe7751b7cea7870377447

@msepga Do you remember if there was a particular reason we dropped this? (since `ext/pg_query/extconf.rb` still references it, maybe this was by accident?)
